version: '3.8'

networks:
  dev:

services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres_backend
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    ports:
      - "8080:8080"
    command: ["webserver"]
    networks:
      dev:

  airflow-scheduler:
    image: apache/airflow:2.10.5
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    command: ["scheduler"]
    networks:
      dev:

  airflow-init:
    image: apache/airflow:2.10.5
    container_name: airflow_init
    restart: on-failure
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    entrypoint: ["/bin/bash", "-c", "airflow db init && airflow db migrate && airflow users create --username airflow --password airflow --role Admin --firstname airflow --lastname airflow --email airflow@airflow.com"]
    networks:
      dev:

volumes:
  postgres_data: